# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50)),
                ('concentration', models.CharField(max_length=100)),
                ('quarter', models.IntegerField()),
                ('numOfCourses', models.IntegerField()),
                ('summer', models.CharField(max_length=10)),
            ],
        ),
    ]
