# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
