# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=120)),
                ('course_name', models.CharField(max_length=120)),
                ('pre_req', models.CharField(max_length=120)),
                ('quarter_ava', models.CharField(max_length=120)),
            ],
        ),
    ]
