# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-14 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IS_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_course_id', models.CharField(max_length=120)),
                ('is_course_name', models.CharField(max_length=120)),
                ('is_pre_req', models.CharField(max_length=120)),
                ('is_quarter_ava', models.CharField(max_length=120)),
            ],
        ),
    ]
