# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-14 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_is_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='is_course',
            name='is_cons',
            field=models.CharField(default=datetime.datetime(2017, 5, 14, 21, 43, 20, 38614, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
