# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-21 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_is_course_is_cons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='is_course',
            name='is_quarter_ava',
        ),
        migrations.AddField(
            model_name='is_course',
            name='fall',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='is_course',
            name='online',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='is_course',
            name='spring',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='is_course',
            name='summer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='is_course',
            name='winter',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
