# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170521_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fall',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='online',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='spring',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='summer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='winter',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
