# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170521_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='quarter_ava',
            new_name='cs_cons',
        ),
    ]
