# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170522_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cs_class_type',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='is_course',
            name='is_class_type',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
